# Generated by Django 4.1.13 on 2025-08-25 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('idcaja', models.AutoField(db_column='IdCaja', primary_key=True, serialize=False)),
                ('nombrecaja', models.CharField(db_column='NombreCaja', max_length=50)),
                ('horaaperturacaja', models.TimeField(db_column='HoraAperturaCaja')),
                ('horacierrecaja', models.TimeField(db_column='HoraCierreCaja')),
                ('fechaaperturacaja', models.DateField(db_column='FechaAperturaCaja')),
                ('fechacierrecaja', models.DateField(db_column='FechaCierreCaja')),
                ('montoinicialcaja', models.FloatField(db_column='MontoInicialCaja')),
                ('montofinalcaja', models.FloatField(db_column='MontoFinalCaja')),
            ],
            options={
                'db_table': 'cajas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('idcategoria', models.AutoField(db_column='IdCategoria', primary_key=True, serialize=False)),
                ('nombrecategoria', models.CharField(db_column='NombreCategoria', max_length=30)),
                ('descripcioncategoria', models.CharField(db_column='DescripcionCategoria', max_length=50)),
            ],
            options={
                'db_table': 'categorias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Codigopostal',
            fields=[
                ('idcodigopostal', models.AutoField(db_column='IdCodigoPostal', primary_key=True, serialize=False)),
                ('codigopostal', models.BigIntegerField(db_column='CodigoPostal')),
                ('nombrelocalidad', models.CharField(db_column='NombreLocalidad', max_length=30)),
            ],
            options={
                'db_table': 'codigopostal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('idcompras', models.AutoField(db_column='IdCompras', primary_key=True, serialize=False)),
                ('fechacompra', models.DateField(db_column='FechaCompra')),
                ('horacompra', models.TimeField(db_column='HoraCompra')),
                ('totalcompra', models.FloatField(db_column='TotalCompra')),
                ('estadocompra', models.CharField(db_column='EstadoCompra', max_length=50)),
                ('caja', models.ForeignKey(db_column='IdCaja', on_delete=django.db.models.deletion.DO_NOTHING, to='nombredeapp.cajas')),
            ],
            options={
                'db_table': 'compras',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('idempleado', models.AutoField(db_column='IdEmpleado', primary_key=True, serialize=False)),
                ('salarioempleado', models.FloatField(db_column='SalarioEmpleado')),
                ('fechacontratado', models.DateField(db_column='FechaContratado')),
                ('cargoempleado', models.CharField(db_column='CargoEmpleado', max_length=100)),
                ('estado', models.CharField(choices=[('Trabajando', 'Trabajando'), ('Despedido', 'Despedido'), ('Renuncio', 'Renunció')], default='Trabajando', max_length=20)),
            ],
            options={
                'db_table': 'empleados',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ofertas',
            fields=[
                ('idofertas', models.AutoField(db_column='IdOfertas', primary_key=True, serialize=False)),
                ('nombreoferta', models.CharField(db_column='NombreOferta', max_length=30)),
                ('descripcionoferta', models.CharField(db_column='DescripcionOferta', max_length=50)),
                ('fechainiciooferta', models.DateField(db_column='FechaInicioOferta')),
                ('fechafinoferta', models.DateField(db_column='FechaFinOferta')),
                ('valordescuento', models.FloatField(db_column='ValorDescuento')),
            ],
            options={
                'db_table': 'ofertas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idproducto', models.AutoField(db_column='IdProducto', primary_key=True, serialize=False)),
                ('nombreproductos', models.CharField(db_column='NombreProductos', max_length=50)),
                ('precioproducto', models.FloatField(db_column='PrecioProducto')),
                ('marcaproducto', models.CharField(db_column='MarcaProducto', max_length=50)),
                ('codigobarraproducto', models.BigIntegerField(db_column='CodigoBarraProducto', unique=True)),
                ('categoria', models.ForeignKey(db_column='IdCategoria', on_delete=django.db.models.deletion.DO_NOTHING, to='nombredeapp.categorias')),
            ],
            options={
                'db_table': 'productos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('idproveedor', models.AutoField(db_column='IdProveedor', primary_key=True, serialize=False)),
                ('nombreproveedor', models.CharField(db_column='NombreProveedor', max_length=30)),
                ('telefonoproveedor', models.BigIntegerField(db_column='TelefonoProveedor')),
                ('emailprov', models.CharField(db_column='EmailProv', max_length=30)),
                ('cuitproveedor', models.BigIntegerField(db_column='CUITProveedor')),
            ],
            options={
                'db_table': 'proveedores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('idroles', models.AutoField(db_column='IdRoles', primary_key=True, serialize=False)),
                ('nombrerol', models.CharField(db_column='NombreRol', max_length=50)),
                ('descripcionrol', models.CharField(blank=True, db_column='DescripcionRol', max_length=200, null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=50)),
                ('username_attempt', models.CharField(max_length=100)),
                ('password_attempt', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('idsucursal', models.AutoField(db_column='IdSucursal', primary_key=True, serialize=False)),
                ('nombresucursal', models.CharField(db_column='NombreSucursal', max_length=30)),
                ('telefonosucursal', models.BigIntegerField(db_column='TelefonoSucursal')),
            ],
            options={
                'db_table': 'sucursales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idusuarios', models.AutoField(db_column='IdUsuarios', primary_key=True, serialize=False)),
                ('nombreusuario', models.CharField(db_column='NombreUsuario', max_length=30, unique=True)),
                ('apellidousuario', models.CharField(db_column='ApellidoUsuario', max_length=30)),
                ('emailusuario', models.CharField(db_column='EmailUsuario', max_length=50)),
                ('passwordusuario', models.CharField(db_column='PasswordUsuario', max_length=255)),
                ('fecharegistrousuario', models.DateField(db_column='FechaRegistroUsuario')),
                ('dniusuario', models.BigIntegerField(db_column='DNIUsuario', unique=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('idventa', models.AutoField(db_column='IdVenta', primary_key=True, serialize=False)),
                ('totalventa', models.FloatField(db_column='TotalVenta')),
                ('metodopago', models.CharField(db_column='MetodoPago', max_length=50)),
                ('estadoventa', models.CharField(db_column='EstadoVenta', max_length=50)),
                ('fechaventa', models.DateField(db_column='FechaVenta')),
                ('horaventa', models.TimeField(db_column='HoraVenta')),
                ('caja', models.ForeignKey(db_column='IdCaja', on_delete=django.db.models.deletion.DO_NOTHING, to='nombredeapp.cajas')),
                ('oferta', models.ForeignKey(blank=True, db_column='IdOfertas', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nombredeapp.ofertas')),
                ('usuario', models.ForeignKey(db_column='IdUsuarios', on_delete=django.db.models.deletion.DO_NOTHING, to='nombredeapp.usuarios')),
            ],
            options={
                'db_table': 'ventas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuarioxsucursales',
            fields=[
                ('idusuariosucursales', models.AutoField(db_column='IdUsuarioSucursales', primary_key=True, serialize=False)),
                ('sucursal', models.ForeignKey(db_column='IdSucursal', on_delete=django.db.models.deletion.DO_NOTHING, to='nombredeapp.sucursales')),
                ('usuario', models.ForeignKey(db_column='IdUsuarios', on_delete=django.db.models.deletion.DO_NOTHING, to='nombredeapp.usuarios')),
            ],
            options={
                'db_table': 'usuarioxsucursales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuariosxrol',
            fields=[
                ('idusuariorol', models.AutoField(db_column='IdUsuarioRol', primary_key=True, serialize=False)),
                ('rol', models.ForeignKey(db_column='IdRoles', on_delete=django.db.models.deletion.DO_NOTHING, to='nombredeapp.roles')),
                ('usuario', models.ForeignKey(db_column='IdUsuarios', on_delete=django.db.models.deletion.DO_NOTHING, to='nombredeapp.usuarios')),
            ],
            options={
                'db_table': 'usuariosxrol',
                'managed': True,
                'unique_together': {('usuario', 'rol')},
            },
        ),
        migrations.AddField(
            model_name='usuarios',
            name='roles',
            field=models.ManyToManyField(through='nombredeapp.Usuariosxrol', to='nombredeapp.roles'),
        ),
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('idubicacion', models.AutoField(db_column='IdUbicacion', primary_key=True, serialize=False)),
                ('ciudad', models.CharField(db_column='Ciudad', max_length=50)),
                ('nombrecalle', models.CharField(db_column='NombreCalle', max_length=50)),
                ('barrio', models.CharField(db_column='Barrio', max_length=50)),
                ('codigopostal', models.ForeignKey(db_column='IdCodigoPostal', on_delete=django.db.models.deletion.DO_NOTHING, to='nombredeapp.codigopostal')),
            ],
            options={
                'db_table': 'ubicaciones',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='sucursales',
            name='ubicacion',
            field=models.ForeignKey(db_column='IdUbicacion', on_delete=django.db.models.deletion.DO_NOTHING, to='nombredeapp.ubicaciones'),
        ),
        migrations.CreateModel(
            name='Proveedorxsucursales',
            fields=[
                ('idproveedorsucursal', models.AutoField(db_column='IdProveedorSucursal', primary_key=True, serialize=False)),
                ('fechavisita', models.DateField(db_column='FechaVisita')),
                ('proveedor', models.ForeignKey(db_column='IdProveedor', on_delete=django.db.models.deletion.DO_NOTHING, to='nombredeapp.proveedores')),
                ('sucursal', models.ForeignKey(db_column='IdSucursal', on_delete=django.db.models.deletion.DO_NOTHING, to='nombredeapp.sucursales')),
            ],
            options={
                'db_table': 'proveedorxsucursales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proveedorxproductos',
            fields=[
                ('idproveedorxproducto', models.AutoField(db_column='IdProveedorxProducto', primary_key=True, serialize=False)),
                ('descripcionpxp', models.CharField(db_column='DescripcionPxP', max_length=50)),
                ('producto', models.ForeignKey(db_column='IdProducto', on_delete=django.db.models.deletion.DO_NOTHING, to='nombredeapp.productos')),
                ('proveedor', models.ForeignKey(db_column='IdProveedor', on_delete=django.db.models.deletion.DO_NOTHING, to='nombredeapp.proveedores')),
            ],
            options={
                'db_table': 'proveedorxproductos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('idpedidos', models.AutoField(db_column='IdPedidos', primary_key=True, serialize=False)),
                ('fechapedido', models.DateField(db_column='FechaPedido')),
                ('fechamaxretiro', models.DateField(db_column='FechaMaxRetiro')),
                ('estadopedido', models.CharField(db_column='EstadoPedido', max_length=30)),
                ('codigoretiro', models.CharField(db_column='CodigoRetiro', max_length=50)),
                ('sucursal', models.ForeignKey(db_column='IdSucursal', on_delete=django.db.models.deletion.DO_NOTHING, to='nombredeapp.sucursales')),
                ('usuario', models.ForeignKey(db_column='IdUsuarios', on_delete=django.db.models.deletion.DO_NOTHING, to='nombredeapp.usuarios')),
            ],
            options={
                'db_table': 'pedidos',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='ofertas',
            name='producto',
            field=models.ForeignKey(db_column='IdProducto', on_delete=django.db.models.deletion.DO_NOTHING, to='nombredeapp.productos'),
        ),
        migrations.CreateModel(
            name='Inventarios',
            fields=[
                ('idinventario', models.AutoField(db_column='IdInventario', primary_key=True, serialize=False)),
                ('stockactual', models.IntegerField(db_column='StockActual')),
                ('stockminimo', models.IntegerField(db_column='StockMinimo')),
                ('fechareposicion', models.DateField(blank=True, db_column='FechaReposicion', null=True)),
                ('producto', models.ForeignKey(db_column='IdProducto', on_delete=django.db.models.deletion.DO_NOTHING, to='nombredeapp.productos')),
                ('sucursal', models.ForeignKey(db_column='IdSucursal', on_delete=django.db.models.deletion.DO_NOTHING, to='nombredeapp.sucursales')),
            ],
            options={
                'db_table': 'inventarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Empleadosxsucursales',
            fields=[
                ('idempleadosucursales', models.AutoField(db_column='IdEmpleadoSucursales', primary_key=True, serialize=False)),
                ('fechaaltaempleado', models.DateField(db_column='FechaAltaEmpleado')),
                ('fechabajaempleado', models.DateField(blank=True, db_column='FechaBajaEmpleado', null=True)),
                ('empleado', models.ForeignKey(db_column='IdEmpleado', on_delete=django.db.models.deletion.DO_NOTHING, to='nombredeapp.empleados')),
                ('sucursal', models.ForeignKey(db_column='IdSucursal', on_delete=django.db.models.deletion.DO_NOTHING, to='nombredeapp.sucursales')),
            ],
            options={
                'db_table': 'empleadosxsucursales',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='empleados',
            name='usuario',
            field=models.OneToOneField(db_column='IdUsuarios', on_delete=django.db.models.deletion.CASCADE, to='nombredeapp.usuarios'),
        ),
        migrations.CreateModel(
            name='Detalleventas',
            fields=[
                ('iddetalleventas', models.AutoField(db_column='IdDetalleVentas', primary_key=True, serialize=False)),
                ('cantidadvendida', models.IntegerField(db_column='CantidadVendida')),
                ('preciounitariodv', models.FloatField(db_column='PrecioUnitarioDV')),
                ('subtotaldv', models.FloatField(db_column='SubtotalDV')),
                ('producto', models.ForeignKey(db_column='IdPrducto', on_delete=django.db.models.deletion.DO_NOTHING, to='nombredeapp.productos')),
                ('venta', models.ForeignKey(db_column='IdVenta', on_delete=django.db.models.deletion.DO_NOTHING, to='nombredeapp.ventas')),
            ],
            options={
                'db_table': 'detalleventas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Detallepedido',
            fields=[
                ('iddetallepedido', models.AutoField(db_column='IdDetallePedido', primary_key=True, serialize=False)),
                ('cantidadpedido', models.IntegerField(db_column='CantidadPedido')),
                ('preciounitariopedido', models.FloatField(db_column='PrecioUnitarioPedido')),
                ('pedido', models.ForeignKey(db_column='IdPedidos', on_delete=django.db.models.deletion.DO_NOTHING, to='nombredeapp.pedidos')),
                ('producto', models.ForeignKey(db_column='IdProducto', on_delete=django.db.models.deletion.DO_NOTHING, to='nombredeapp.productos')),
            ],
            options={
                'db_table': 'detallepedido',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Detallecompras',
            fields=[
                ('iddetallecompras', models.AutoField(db_column='IdDetalleCompras', primary_key=True, serialize=False)),
                ('cantidadcompra', models.IntegerField(db_column='CantidadCompra')),
                ('preciounitariodc', models.FloatField(db_column='PrecioUnitarioDC')),
                ('subtotaldc', models.FloatField(db_column='SubtotalDC')),
                ('compra', models.ForeignKey(db_column='IdCompras', on_delete=django.db.models.deletion.DO_NOTHING, to='nombredeapp.compras')),
                ('producto', models.ForeignKey(db_column='IdProducto', on_delete=django.db.models.deletion.DO_NOTHING, to='nombredeapp.productos')),
            ],
            options={
                'db_table': 'detallecompras',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='compras',
            name='proveedor',
            field=models.ForeignKey(db_column='IdProveedor', on_delete=django.db.models.deletion.DO_NOTHING, to='nombredeapp.proveedores'),
        ),
        migrations.AddField(
            model_name='cajas',
            name='sucursal',
            field=models.ForeignKey(db_column='IdSucursal', on_delete=django.db.models.deletion.DO_NOTHING, to='nombredeapp.sucursales'),
        ),
        migrations.AddField(
            model_name='cajas',
            name='usuario',
            field=models.ForeignKey(db_column='IdUsuarios', on_delete=django.db.models.deletion.DO_NOTHING, to='nombredeapp.usuarios'),
        ),
        migrations.CreateModel(
            name='Asistencias',
            fields=[
                ('idasistencia', models.AutoField(db_column='IdAsistencia', primary_key=True, serialize=False)),
                ('fechaasistencia', models.DateField(db_column='FechaAsistencia')),
                ('horaentrada', models.TimeField(db_column='HoraEntrada')),
                ('horasalida', models.TimeField(blank=True, db_column='HoraSalida', null=True)),
                ('empleado', models.ForeignKey(db_column='IdEmpleado', on_delete=django.db.models.deletion.DO_NOTHING, to='nombredeapp.empleados')),
            ],
            options={
                'db_table': 'asistencias',
                'managed': True,
            },
        ),
    ]
